apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}

